### ISSUE TITLE
sqlite3 error with iris solution 

### ISSUE THREAD

**Issue by ghost** [kataras/go-fs#1]
@kataras  please update repo 
[solution](https://github.com/mattn/go-sqlite3/issues/329)

**Comment by kataras** [comment]
Oh ok, just a moment

**Comment by ghost** [comment]
```
Okay I figure out. Try to remove this.

rm -rf $GOPATH/src/github.com/kataras/go-fs/vendor/github.com/klauspost/crc32
rm -rf $GOPATH/src/github.com/kataras/go-fs/vendor/github.com/klauspost/compress
```

I can't remove klauspost/compress from iris and go-fs because it has the fastest algorithm I ever see for compression, so I will try to just remove them from the vendor, but I have to tell you that the go get will install it as dependecy when installing iris/go-fs

**Comment by ghost** [comment]
Ok, done try to remove your `$GOPATH/src/github.com/kataras` and `$GOPATH/src/github.com/klauspost` and exec `go get -u github.com/kataras/iris` tell me if that is working please

**Comment by ghost** [comment]
@kataras   working fine thank you
