### ISSUE TITLE
Update package to use context.Context for go-github calls

### ISSUE THREAD

**Issue by bradbyte** [kataras/go-fs#2]
Hello,

I'm utilizing your Iris router on a project and am now unable to deploy my app because of this error:

```
remote: vendor/github.com/kataras/go-fs/updater.go:62: not enough arguments in call to client.Repositories.GetLatestRelease
remote: 	have (string, string)
remote: 	want (context.Context, string, string)
```

Reading this [issue on go-github](https://github.com/google/go-github/issues/526), it seems they've made a breaking API change that requires `context.Context` as the first param on all methods. I'm not sure how you want to handle the context, but I was able to get my local project working by passing a new instance of context from `context.TODO()` to the call. I can make a PR with what I did for your review.

Thanks!

**Comment by bliuchak** [comment]
@kataras, are you planning to make an new release for `gopkg.in/kataras/go-fs.v0`?
